openapi: 3.1.0
info:
  title: User Management Service
  description: A service for managing user accounts
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '201':
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-features:
        - userRegistration

  /auth/login:
    post:
      tags:
        - Auth
      summary: User login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-features:
        - userLogin

  /users:
    parameters:
      - $ref: '#/components/parameters/Authorization'
    get:
      tags:
        - Users
      summary: Get list of users
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-features:
        - listUsers

  /users/{id}:
    parameters:
      - $ref: '#/components/parameters/Authorization'
    get:
      tags:
        - Users
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            example: 1000
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-features:
        - getUserById

    delete:
      tags:
        - Users
      summary: Delete user by ID
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful deletion
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-features:
        - deleteUser

  /users/{id}/changePassword:
    parameters:
      - $ref: '#/components/parameters/Authorization'
    post:
      tags:
        - Users
      summary: Change user password
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
        required: true
      responses:
        '200':
          description: Successful password change
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-features:
        - changeUserPassword

  /users/{id}/deactivate:
    parameters:
      - $ref: '#/components/parameters/Authorization'
    post:
      tags:
        - Users
      summary: Deactivate user
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful deactivation
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-features:
        - deactivateUser

  /users/{id}/activate:
    parameters:
      - $ref: '#/components/parameters/Authorization'
    post:
      tags:
        - Users
      summary: Activate user
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful activation
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-features:
        - activateUser

components:
  parameters:
    Authorization:
      name: token
      in: header
      schema:
        type: string
        format: string
      required: true

  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          description: Status code
        message:
          type: string
          description: Error description

    LoginRequest:
      type: object
      properties:
        login:
          type: string
          description: Email або username
        password:
          type: string
      required:
        - login
        - password

    ChangePasswordRequest:
      type: object
      properties:
        old_password:
          type: string
        new_password:
          type: string
      required:
        - old_password
        - new_password

    UserRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        first_name:
          type: string
        last_name:
          type: string
      required:
        - username
        - email
        - password

    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        role:
          type: string
          enum: [ admin, user, guest ]
          readOnly: true
        is_active:
          type: boolean
          readOnly: true
        is_deleted:
          type: boolean
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        modified_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - id
        - username
        - email

  x-features:
    userRegistration:
      description: Registering new users
    userLogin:
      description: User authentication
    listUsers:
      description: Retrieving a list of users
    getUserById:
      description: Retrieving a user by ID
    deleteUser:
      description: Deleting users
    changeUserPassword:
      description: Changing user passwords
    deactivateUser:
      description: Deactivating user accounts
    activateUser:
      description: Activating user accounts

